sudo: required
services:
    - docker

before_install:
    - docker build -t avillacres/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true avillacres/react-test npm test -- --coverage

after_success:
    - docker build -t avillacres/multi-client ./client
    - docker build -t avillacres/multi-nginx ./nginx
    - docker build -t avillacres/multi-server ./server
    - docker build -t avillacres/multi-worker ./worker

#login to travis
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#push to docker hub
    - docker push avillacres/multi-client
    - docker push avillacres/multi-nginx
    - docker push avillacres/multi-server
    - docker push avillacres/multi-worker

deploy:
    provider: elasticbeanstalk
    region: 'us-east-2'
    app: 'multi-docker'
    env: 'MultiDocker-env'
    bucket_name: 'elasticbeanstalk-us-east-2-928850819422'
    bucket_path: 'docker-multi'
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
