sudo: required
services:
    - docker

before_install:
    - docker build -t avillacres/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run avillacres/react-test npm test -- --coverage

after_success:
    - docker build -t avillacres/multi-client -f ./client
    - docker build -t avillacres/multi-nginx -f ./nginx
    - docker build -t avillacres/multi-server -f ./server
    - docker build -t avillacres/multi-worker -f ./worker

#login to travis
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#push to docker hub
    - docker push avillacres/multi-client
    - docker push avillacres/multi-nginx
    - docker push avillacres/multi-server
    - docker push avillacres/multi-worker